[target.x86_64-unknown-none]
rustflags = [
  "-C",
  "force-frame-pointers",
  "-C",
  "link-arg=-Tmisc/x86_64.ld",
  "-C",
  "link-arg=--gc-sections",
  "-C",
  "codegen-units=1",
]
runner = "./scripts/root.sh"

[unstable]
build-std = ["core", "alloc"]
json-target-spec = true

[build]
target = "x86_64-unknown-none"

[alias]
build-modules = "build -p cmos --target misc/ktmodule.json"